### ISSUE TITLE
Display a text department wise

### ISSUE THREAD

**Issue by DEVDASTUDIO** [SocialGouv/react-departements#136]
Hi,

Is it possible to display a some text on each departmen? which we are passing from departements.

```<France departements={[75, 89, 21, 33, 47, 74, "2a", 976]} />;```

Thanks

**Comment by revolunet** [comment]
Hi, not possible at the moment, but happy to help land a pull request for it

**Comment by revolunet** [comment]
One could imagine a retro compatible API that could handle both formats, for example

`const dtps = [{id: 75, text:"Ici c'est Paris!", background: "blue"}, 89, 21, 33, 47, 74, "2a", 976]} />;`

Another option is using React:

```jsx
<France>
   <Departement id="75">Some text for <b>Paris</b></Department>
   <Departement id="23" backgroundColor="pink"/>
</France>
```

Now, as the map is SVG based, how should the overlay be displayed ?

**Comment by DEVDASTUDIO** [comment]
Actually I'm trying to update svg map based on dynamic data change from dropdown. Please have a look on my attached screenshot.

![image](https://user-images.githubusercontent.com/48910877/103518333-053a6380-4e8d-11eb-85fe-e1cc191ebdb2.png)

**Comment by revolunet** [comment]
this is "regions" not "departements" so you'd better use [svg-maps](https://github.com/VictorCazanave/svg-maps) or similar imho

As departements are smaller areas, only an overlay on mouseover could fit i guess.
